webpack.config.js

https://github.com/roam-unofficial/roam-toolkit/issues/4

fixes issue #4 

---

tsconfig.json
webpack.config.js

This is part of a larger change to support vim style navigation (#63)
I think absolute imports are easier to read in some cases, since otherwise the import would be like something like `../../../../core/roam`.
I've been using absolute imports when reusing generic utilities, but using relative imports if I'm importing something in the same folder, since the import would just be `./my-package-private-module`

Vim Mode 1 - Allow absolute imports

---

tests/ts/components/styles/themes/index.test.ts
tests/ts/core/roam/date/withDate.test.ts
tests/ts/core/roam/roam-node.test.ts
tests/ts/core/srs/AnkiScheduler.test.ts

Accidentally broke tests with https://github.com/roam-unofficial/roam-toolkit/pull/93, fixed by updating the imports

Fix tests by updating import paths

---

webpack.config.js

Fixes an issue in https://github.com/roam-unofficial/roam-toolkit/pull/109
Previously, the `manifest.json` was only overridden when running `npm run dev`, but upon running `npm run watch`, `manifest.json` would revert to it's original state.
This makes it so the manifest file is tweaked in both development and watch modes

Override manifest.json in both watch and development mode

---

src/ts/core/roam/roam-node.ts

So for SRS it'd go from `[[[[interval]]:3]]` to `{[[interval]]:3}`

Swich the inline property to be surrounded by {} instead of [[]]

---

src/ts/core/features/vim-mode/commands/clipboard-commands.ts
src/ts/core/features/vim-mode/roam/roam-block.ts
src/ts/core/features/vim-mode/roam/roam-event.ts
src/ts/core/features/vim-mode/roam/roam-panel.ts
src/ts/core/roam/selectors.ts

This fixes #100.
It also simplifies the relative block navigation, because the block index is directly manipulated as the source of truth, rather than converting `BlockId` => `BlockIndex` => back to `BlockId`
Here's a demo of preserving position with SRS shortcuts:
This also fixes an issue where the selection is lost when editing blocks inside of references.

Save the selected block's index, instead of it's id

---

src/ts/core/common/mouse.ts

For some reason, the fold caret inside of references needs a mouse **move**, rather than a mouse **over**

Fix folding within references

---

src/ts/core/roam/roam.ts

Closes https://github.com/roam-unofficial/roam-toolkit/issues/125
The issue was that normal blocks are siblings of the fold caret, but headings are _children_ of siblings of the fold caret

Fix folding headings

---

src/ts/core/common/array.ts
src/ts/core/features/vim-mode/roam/roam-panel.ts

This undoes the changes in https://github.com/roam-unofficial/roam-toolkit/pull/116, and uses `blockIndex` as a fallback for `blockId` instead.
Rescheduling Dates:
Remember block when opening in sidebar
Blocks inserted before
I didn't figure out how to make it so your main page resets to the first block when you switch pages.
The issue is that the main panel persists even when you switch pages. In order to reset the block upon switching main pages, I have to detect whether the main page changed. This doesn't seem trivial though, because even when you swap pages, the `.roam-article` div remains intact.

Use blockId as a fallback, rather than source of truth

---

src/ts/core/features/vim-mode/commands/navigation-commands.ts
src/ts/core/features/vim-mode/roam/roam-panel.ts
src/ts/core/features/vim-mode/vim-init.ts

Turns out it's actually pretty easy to select the first block, the `onChangePage` event works fine

Select first block when switching pages

---

README.md
src/ts/core/features/filter-search.ts
src/ts/core/features/index.ts
src/ts/core/roam/selectors.ts

Search pages in page or references filter

---

src/ts/core/features/vim-mode/commands/navigation-commands.ts
src/ts/core/roam/references.ts
src/ts/core/roam/selectors.ts

This allows opening the parent page when selecting a block in linked references
Not sure what the most intuitive shortcut would be, so I just picked `1`

Shortcuts to open pages in linked references

---

src/ts/core/roam/references.ts
src/ts/core/roam/selectors.ts

This makes "Open Parent Page" click the **title**, if the block is at the top level (not inside a reference).
This makes it easier to rename pages, and "throw" pages between the main/sidebar

Extend "Open Parent Page" to also click titles

---

src/ts/core/features/index.ts
src/ts/core/features/random-page.ts
src/ts/core/features/vim-mode/commands/insert-commands.ts
src/ts/core/roam/roam-db.ts
src/ts/core/roam/roam-node.ts
src/ts/core/roam/roam.ts

[Demo Video](https://www.youtube.com/watch?v=1mofhCa776U)
* `ctrl+shift+?` inserts a random link in the currently focused block
* `ctrl+command+shift+?` inserts a link, and then opens in the sidebar
* Also provides a regex to exclude pages such as SRS metadata, and Daily Notes
This also adds the `Roam.moveCursorToSearchTerm` helper, which might be helpful for navigating the cursor around in a block.
Also, I think I finally figured out why the `insert block after` shortcut was unreliable for me in vim mode. It's because when `Roam.save` triggers the "input" event, it resets the cursor selection. I delayed the cursor selection until after the input event is handled. Otherwise, the selection sometimes doesn't get applied.

Shortcut to insert random page, open random pages in the sidebar

---

src/ts/core/features/random-page.ts

This fixes the unescaped regex in https://github.com/roam-unofficial/roam-toolkit/pull/148

Oops, properly escape the \d for opening random page

---

src/ts/core/features/vim-mode/commands/navigation-commands.ts
src/ts/core/roam/references.ts
src/ts/core/roam/selectors.ts

This fixes https://github.com/roam-unofficial/roam-toolkit/issues/166
It also adds a shortcut to open mentions:
If the block has mentions, this opens the block's mentions
If the block has no mentions, this open's the page's mentions
So this is kind of like "open the mentions for whatever is selected"

Fix folding blocks in Vim Mode. Also add shortcut to open mentions

---

src/ts/core/features/vim-mode/roam/roam-event.ts
src/ts/core/roam/selectors.ts

Fixes #173 
Previously, Roam's structure was:
```
`roam-main`
-- `roam-body-main` (observe content from here)
---- `roam-article` <- changes when navigating to/from daily notes
------ `div` <- changes when navigating between pages 
```
Now, Roam's structure is:
```
`roam-main`
-- `roam-body-main` <- changes when navigating to/from daily notes (destroying content observer)
---- `roam-article`
------ `div` <- changes when navigating between pages 
```
To avoid destroying the content observer, we move the observer one level up:
```
`roam-main` (observe content from here)
-- `roam-body-main` <- changes when navigating to/from daily notes (destroying content observer)
---- `roam-article`
------ `div` <- changes when navigating between pages 
```

Fix navigating between daily notes in vim mode

---

src/ts/core/roam/references.ts

Sidebar panels now behave like main pages, this makes `1` rename it.

Make `1` rename sidebar pages in Vim Mode

---

src/ts/core/features/vim-mode/hint-view.ts

I've been running into blocks with 7 links more often lately, figured I'd add another hint

Add another vim hint

---

src/ts/core/common/mouse.ts
src/ts/core/common/platform.ts
src/ts/core/features/vim-mode/commands/hint-commands.ts
src/ts/core/roam/references.ts

I learned that you can open mentions of a link with `ctrl+shift+click`. This exposes that via the vim hints

Allow opening mentions of a link with ctrl+shift+hint

---

src/ts/core/features/spatial-mode/index.ts

Oops, I forgot that disabling drag and drop for the headers would also affect drag and drop for the bullets.

Fix drag and dropping bullets in spatial sidebars

---

src/ts/core/features/spatial-mode/spatial-container.ts

This fixes an issue where panels rise above the topbar. Also, it makes the sidebar not move around when opening pages.

Fix CSS for topbar in spatial mode

---

src/ts/core/features/spatial-mode/graph-visualization.ts

I ran into a bug where a certain sidebar page wasn't forking new pages off of it. Opened links just were just disconnected. It only happened when forking from that particular sidebar page though.
I narrowed it down to Cytoscape mistakenly thinking that the edge had already been drawn. (It refuses to draw a duplicate edge in this case).
When I checked for the duplicate edge in the debugger, I saw that the Cytoscape filter was selecting the incorrect edges:
```javascript
// Try to look for edges from Foo -> Bar
this.cy.$(`edge[source = "Foo"][target = "Bar"]`).target().id() // "Baz"
// It found an edge that didn't even go to Bar
```
It might've had something to emojis being in the title. I switched it to explicitly filtering and comparing ids, which seemed to fix the problem.

Fix sidebar panels fail to connect to each other occasionally (maybe has to do with emojis in titles?)
